map_saver:
  ros__parameters:
    use_sim_time: True
    save_map_timeout: 5000 # Este parámetro, soluciona el problema del timeout en la distribución Foxy (Solved in Galactic and further)
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65